### PR TITLE
Remove "under development" in README; add warning about username

### PR DESCRIPTION
**Pull request by lxylxy123456**
Remove "This service is under development. Use this at your own risk."
Add warning about reusing usernames

### CODE REVIEW

**Comment by lxylxy123456** [comment]
@rkevin-arch I added the paragraph. What about now?

**Comment by Lawrence37** [comment]
What stage do we consider ngshare to be in (beta, release candidate, etc.)?

**Comment by lxylxy123456** [comment]
I do not have experience in releasing before. Maybe release candidate? (and at the end of this quarter it can be stable release). 
Do we have to put this status somewhere (e.g. in README)?

**Comment by rkevin-arch** [comment]
probably release candidate, imo

**Pull request merged**
