### PR TITLE
401 when not logged in

### PR DESCRIPTION
**Pull request by lxylxy123456**
In response to #57
However, I would say that this solution is not optimal, and may break when Tornado server is updated.

### CODE REVIEW

**Comment by rkevin-arch** [comment]
I can make the change; shouldn't be too hard. The original code is [here](https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/services/auth.py) and porting it over shouldn't be too hard. The main downside is if upstream updates this code, we have to maintain it separately. The upside is we can make all the error messages uniform (if they have an error, their error message is not json and won't follow our `{"success": "false"}` convention) and change the status codes however we like. It also removes the need to install JupyterHub in the ngshare container just for that one dependency. Not sure if we should do that.

**Comment by rkevin-arch** [comment]
BTW, there is a small but nonzero chance the `HubAuthenticated` code will return status codes like 500, 403 or 400. We might want to document this.

**Comment by lxylxy123456** [comment]
@rkevin-arch the problem is the `@authenticated` decorator. I think we shouldn't spend too much time on this.

**Comment by lxylxy123456** [comment]
Also don't make this project too complicated.

**Comment by rkevin-arch** [comment]
fair

**Comment by rkevin-arch** [comment]
So we're saying our error messages might not always be JSON? If `@authenticated` gives an error for whatever reason, it won't be JSON.

**Comment by lxylxy123456** [comment]
Well, I don't know how to handle this case. It is similar to what happens if you GET `/api/random-string`. For example, Canvas says everything is in JSON (in https://canvas.instructure.com/doc/api/index.html), but they use HTML 404 page for `/api/random-string`

**Pull request closed without merging**
