### PR TITLE
Merge sudo

### PR DESCRIPTION
**Pull request by lxylxy123456**
This branch is the result of merging all PRs that are dependent on sudo branch

### CODE REVIEW

**Comment by willingc** [comment]
Just curious...what is the workflow that you are using for the project?

**Comment by lxylxy123456** [comment]
Maybe just Ad Hoc Model. The good thing is there is no production use at this time.

**Comment by willingc** [comment]
@lxylxy123456 The reason I ask is that a large PR like this merging other stuff is kind of an open source anti-pattern. Totally fine for now. Just pro tip for the future.

**Comment by lxylxy123456** [comment]
Merged in other PRs

**Pull request closed without merging**
