### PR TITLE
Updates for the API specifications

### PR DESCRIPTION
**Pull request by Lawrence37**
This is for discussing and making changes to the API specifications.

The first change is the addition of a GET request for listing the courses a user can access.

Changes desired:

- [x] Get courses
- [x] List notebooks in an assignment
- [x] Define timestamp format (#4)
- [ ] Add `student_id` to GET a student's submissions (#6)
- [ ] Clarify which submission should be fetched (#7)
- [x] Fix placement of timestamp field
- [x] Make feedback requests use directory trees

### CODE REVIEW

**Comment by Lawrence37** [comment]
#3 #4

**Comment by Lawrence37** [comment]
#6

**Comment by lxylxy123456** [comment]
1. Make sure to specify how to pass in `list_only` argument. It should be one of the follows:
```
HTTP GET json_arguments={
    "list_only": true
}
```
or
```
HTTP GET list_only=true
```

2. We may want to add an example of list_only in [Directory tree](https://github.com/lxylxy123456/ngshare/blob/api_specifications/api-specifications.md#directory-tree) section

3. Do we need some metadata? Like file size?

**Comment by Lawrence37** [comment]
>     1. Make sure to specify how to pass in list_only argument.
I specified it as JSON, but maybe it could be better as a parameter?

>     1. We may want to add an example of list_only in Directory tree section
Can you tell me in what ways the structure is ambiguous?

>     2. Do we need some metadata? Like file size?
No metadata necessary.

**Comment by lxylxy123456** [comment]
1. Can you give me an example of URL to access this API? Then you may see something wrong
2. See 4
3. OK
4. I think we should also allow `list_only` in `/api/assignment/<course_id>/<assignment_id>`. And add an example like (the current version is not ambiguous, but reading an example is easier than reading a bunch of text):
```
[
    {
        "path": /* file path relative to the root */
    },
    ...
]
```
5. If no meta data required, can we make it the following?
```
[
    "path": /* file path relative to the root */,
    ...
]
```

**Comment by Lawrence37** [comment]
If using JSON, a URL can be `http://server/api/assignment/course0/assignment0`. If using a parameter, `http://server/api/assignment/course0/assignment0?list_only=true`.

I will add `list_only` to the get assignment request. I don't know about the JSON structure. It would be nice to use the same structure regardless of the value for `list_only`.

**Comment by lxylxy123456** [comment]
My point is that if you are using JSON, it will look like `http://server/api/assignment/course0/assignment0?json_parameters={list_only: true}`. Note that you cannot send anything in HTTP GET body. So yes, I think using `http://server/api/assignment/course0/assignment0?list_only=true` is better.

**Comment by lxylxy123456** [comment]
Also change these:
1. https://github.com/lxylxy123456/ngshare/blob/api_specifications/api-specifications.md#request-3
2. https://github.com/lxylxy123456/ngshare/blob/api_specifications/api-specifications.md#request-6
    2a. Note that timestamp should be generated by server and returned in response (or student can submit after deadline) 
3. https://github.com/lxylxy123456/ngshare/blob/api_specifications/api-specifications.md#request-8
    3a. We want to make feedback also using "Directory tree" structure (it is how the database is designed). 
    3b. Why is there a timestamp for every notebook file's feedback? (I think it should be the submission time stamp)

**Comment by Lawrence37** [comment]
What changes do you want me to make to the first two requests you mentioned?

I will see about using a directory tree. Also, the timestamp placement is a mistake. There should only be one for each submission.

**Comment by lxylxy123456** [comment]
For example, the second one should be 
```
...?timestamp=submission_time_stamp&files=[json_encoded_file_list]
```
Currently these looks like passing a json object to HTTP GET

**Comment by Lawrence37** [comment]
The two requests use POST.

**Comment by lxylxy123456** [comment]
I see. Would you like to change "Request" to "Request body" and "Response" to "Response body when success"? (consider merging #8 before doing this)

Also, when Request is None, we can remove them (e.g. [this](https://github.com/lxylxy123456/ngshare/blob/api_specifications/api-specifications.md#request))

**Comment by lxylxy123456** [comment]
Even it is post, I think we should still avoid sending a JSON object in the entire data. We should still use file=[...] in post body.

**Pull request merged**
