### PR TITLE
Course management

### PR DESCRIPTION
**Pull request by aalmanza1998**
Use python commands to manage a course. See README for details

### CODE REVIEW

**Comment by lxylxy123456** [comment]
If I run `python3 ngshare_management.py`, I get 
```
Traceback (most recent call last):
  File "ngshare_management.py", line 395, in <module>
    sys.exit(main())
  File "ngshare_management.py", line 389, in main
    command, optlist = parse_input(argv)
  File "ngshare_management.py", line 325, in parse_input
    command = (argv[1]).lower()
IndexError: list index out of range
```
Line 321 should probably be `if len(argv) <= 1:`

@aalmanza1998 I will review more later. Should I be running it in a JupyterHub account?

**Comment by lxylxy123456** [comment]
Do you want to use something like `argparse` to parse arguments?

**Comment by aalmanza1998** [comment]
> If I run `python3 ngshare_management.py`, I get
> 
> ```
> Traceback (most recent call last):
>   File "ngshare_management.py", line 395, in <module>
>     sys.exit(main())
>   File "ngshare_management.py", line 389, in main
>     command, optlist = parse_input(argv)
>   File "ngshare_management.py", line 325, in parse_input
>     command = (argv[1]).lower()
> IndexError: list index out of range
> ```
> 
> Line 321 should probably be `if len(argv) <= 1:`
> 

Yes, I added the `--help` flag forgot to modify to modify that line. I've fixed it now, thank you! Yes, please test in JupyterHub.

**Comment by aalmanza1998** [comment]
> Do you want to use something like `argparse` to parse arguments?

I used `getopt.getopt` but I can switch to `argparse` if ya'll would like me to.

**Comment by lxylxy123456** [comment]
If we change to argparse:
1. For some reason argparse seems to be more popular: 图片 
2. Consistent with ngshare
3. Personally I think argparse is more robost

@aalmanza1998 I think I will take over the changing job. You can worry more about other aspects & JupyterLab. 

Are you using some coding style standard?

**Comment by aalmanza1998** [comment]
> If we change to argparse:
> 
> 1. For some reason argparse seems to be more popular: 图片
> 2. Consistent with ngshare
> 3. Personally I think argparse is more robost
> 
> @aalmanza1998 I think I will take over the changing job. You can worry more about other aspects & JupyterLab.
> 
> Are you using some coding style standard?

It's ok, I'll make the switch to argparse.

**Comment by aalmanza1998** [comment]
Need to test after these changes.

**Comment by aalmanza1998** [comment]
Closing this because we are moving this script to the ngshare_exchange repo.

**Pull request closed without merging**
